<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<UseWindowsForms>true</UseWindowsForms>
	<ImplicitUsings>disable</ImplicitUsings>
	<Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Covers\default.png" />
    <None Remove="Assets\Covers\default_pdf.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Covers\default.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Icons\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Docnet.Core" Version="2.6.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.6" />
    <PackageReference Include="PdfPig" Version="0.1.14" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="VersOne.Epub" Version="3.3.6" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\Covers\default_epub_old.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
